export interface DnaMarker {
  id: string;
  name: string;
  desc?: string; // Made optional for v4 dataset
}

export interface DnaLayer {
  id: string;
  name: string;
  markers: DnaMarker[];
}

export const DNA_LAYERS: DnaLayer[] = [
  {
    "id": "L0",
    "name": "Raw Waveform",
    "markers": [
    {"id": "W1", "name": "RMS energy"},
    {"id": "W2", "name": "Peak amplitude"},
    {"id": "W3", "name": "Crest factor"},
    {"id": "W4", "name": "Zero-crossing rate"},
    {"id": "W5", "name": "DC offset"},
    {"id": "W6", "name": "Dynamic range"},
    {"id": "W7", "name": "Stereo width"},
    {"id": "W8", "name": "Stereo correlation"},
    {"id": "W9", "name": "Mid energy"},
    {"id": "W10", "name": "Side energy"},
    {"id": "W11", "name": "Phase coherence"},
    {"id": "W12", "name": "Peak-to-average"},
    {"id": "W13", "name": "Clipping detect"},
    {"id": "W14", "name": "Noise floor"},
    {"id": "W15", "name": "THD"},
    {"id": "W16", "name": "IMD"},
    {"id": "W17", "name": "Jitter"},
    {"id": "W18", "name": "Wow"},
    {"id": "W19", "name": "Flutter"},
    {"id": "W20", "name": "Hum 50Hz"},
    {"id": "W21", "name": "Hum 60Hz"},
    {"id": "W22", "name": "Vinyl crackle"},
    {"id": "W23", "name": "Tape hiss"},
    {"id": "W24", "name": "Digital aliasing"},
    {"id": "W25", "name": "Bit depth"},
    {"id": "W26", "name": "Sample rate artifacts"},
    {"id": "W27", "name": "MP3 artifacts"},
    {"id": "W28", "name": "Dropout"},
    {"id": "W29", "name": "Reverse detect"},
    {"id": "W30", "name": "Silence"},
    {"id": "W31", "name": "Fade in"},
    {"id": "W32", "name": "Fade out"}
    ]
    },
    {
    "id": "L1",
    "name": "Micro-Rhythm",
    "markers": [
    {"id": "R1", "name": "16th-note guitar"},
    {"id": "R2", "name": "32nd-note guitar"},
    {"id": "R3", "name": "Fingerpick nylon"},
    {"id": "R4", "name": "Fingerpick steel"},
    {"id": "R5", "name": "Flatpick alternate"},
    {"id": "R6", "name": "Flatpick economy"},
    {"id": "R7", "name": "Kick on 1"},
    {"id": "R8", "name": "Kick on 1&3"},
    {"id": "R9", "name": "Kick syncopated"},
    {"id": "R10", "name": "Snare on 2&4"},
    {"id": "R11", "name": "Snare on 3"},
    {"id": "R12", "name": "Rim-shot"},
    {"id": "R13", "name": "Cross-stick"},
    {"id": "R14", "name": "Humanized swing"},
    {"id": "R15", "name": "808 sub pulse"},
    {"id": "R16", "name": "909 kick"},
    {"id": "R17", "name": "Clap layer"},
    {"id": "R18", "name": "Clap stack"},
    {"id": "R19", "name": "Ghost notes"},
    {"id": "R20", "name": "Flam"},
    {"id": "R21", "name": "Hi-hat 16ths closed"},
    {"id": "R22", "name": "Hi-hat 16ths open"},
    {"id": "R23", "name": "Hi-hat 8ths"},
    {"id": "R24", "name": "Hi-hat pedal chick"},
    {"id": "R25", "name": "Ride cymbal bell"},
    {"id": "R26", "name": "Ride cymbal bow"},
    {"id": "R27", "name": "Ride cymbal edge"},
    {"id": "R28", "name": "Tambourine 8ths"},
    {"id": "R29", "name": "Tambourine 16ths"},
    {"id": "R30", "name": "Shaker continuous"},
    {"id": "R31", "name": "Shaker accented"},
    {"id": "R32", "name": "Cowbell"},
    {"id": "R33", "name": "Woodblock high"},
    {"id": "R34", "name": "Woodblock low"},
    {"id": "R35", "name": "Triangle"},
    {"id": "R36", "name": "Tom fill 8ths"},
    {"id": "R37", "name": "Tom fill 16ths"},
    {"id": "R38", "name": "Tom fill 32nds"},
    {"id": "R39", "name": "Double-kick 16ths"},
    {"id": "R40", "name": "Blast beat"},
    {"id": "R41", "name": "D-beat"},
    {"id": "R42", "name": "Djembe bass tone"},
    {"id": "R43", "name": "Djembe slap"},
    {"id": "R44", "name": "Cajon bass"},
    {"id": "R45", "name": "Cajon slap"},
    {"id": "R46", "name": "Bongo high"},
    {"id": "R47", "name": "Bongo low"},
    {"id": "R48", "name": "Conga open"},
    {"id": "R49", "name": "Conga slap"},
    {"id": "R50", "name": "Conga mute"},
    {"id": "R51", "name": "Timbale shell"},
    {"id": "R52", "name": "Timbale head"},
    {"id": "R53", "name": "Maraca"},
    {"id": "R54", "name": "Guiro scrape"},
    {"id": "R55", "name": "Cabasa roll"},
    {"id": "R56", "name": "Vibraslap"},
    {"id": "R57", "name": "Agogo bell high"},
    {"id": "R58", "name": "Agogo bell low"},
    {"id": "R59", "name": "Flexatone"},
    {"id": "R60", "name": "Ratchet"},
    {"id": "R61", "name": "Whistle"},
    {"id": "R62", "name": "Claves"},
    {"id": "R63", "name": "Castanets"},
    {"id": "R64", "name": "Finger snap"}
    ]
    },
    {
    "id": "L2",
    "name": "Psychoacoustic Spectra",
    "markers": [
    {"id": "S1", "name": "ERB Sub-Bass (20-100Hz)"},
    {"id": "S2", "name": "ERB Bass/Low-Mid (100-800Hz)"},
    {"id": "S3", "name": "ERB Mid-Range (800-2.5kHz)"},
    {"id": "S4", "name": "ERB Upper-Mid (2.5-8kHz)"},
    {"id": "S5", "name": "ERB High (8-14kHz)"},
    {"id": "S6", "name": "ERB Air (14-20kHz)"}
    ]
    },
    {
    "id": "L3",
    "name": "Harmonic DNA",
    "markers": [
    {"id": "H1", "name": "I-IV-V progression"},
    {"id": "H2", "name": "ii-V-I progression"},
    {"id": "H3", "name": "Dorian mode"},
    {"id": "H4", "name": "Phrygian mode"},
    {"id": "H5", "name": "Lydian mode"},
    {"id": "H6", "name": "Mixolydian mode"},
    {"id": "H7", "name": "Aeolian mode"},
    {"id": "H8", "name": "Locrian mode"},
    {"id": "H9", "name": "Pentatonic Minor"},
    {"id": "H10", "name": "Pentatonic Major"},
    {"id": "H11", "name": "Blues Scale"},
    {"id": "H12", "name": "Whole Tone"},
    {"id": "H13", "name": "Chromatic run"},
    {"id": "H14", "name": "Sus2 chord"},
    {"id": "H15", "name": "Sus4 chord"},
    {"id": "H16", "name": "Add9 chord"},
    {"id": "H17", "name": "Maj7 chord"},
    {"id": "H18", "name": "Min7 chord"},
    {"id": "H19", "name": "Dom7 chord"},
    {"id": "H20", "name": "Dim7 chord"},
    {"id": "H21", "name": "Augmented chord"},
    {"id": "H22", "name": "6/9 chord"},
    {"id": "H23", "name": "11th extension"},
    {"id": "H24", "name": "13th extension"},
    {"id": "H25", "name": "Power chord (no 3rd)"},
    {"id": "H26", "name": "Parallel 5ths"},
    {"id": "H27", "name": "Tritone substitution"},
    {"id": "H28", "name": "Quartal harmony"},
    {"id": "H29", "name": "Tone cluster"},
    {"id": "H30", "name": "Pedal point"},
    {"id": "H31", "name": "Picardy third"},
    {"id": "H32", "name": "Key modulation"},
    {"id": "H33", "name": "Neapolitan 6th"},
    {"id": "H34", "name": "German 6th"},
    {"id": "H35", "name": "French 6th"},
    {"id": "H36", "name": "Italian 6th"},
    {"id": "H37", "name": "Secondary Dominant"},
    {"id": "H38", "name": "Altered Scale"},
    {"id": "H39", "name": "Octatonic Scale"},
    {"id": "H40", "name": "Harmonic Minor"},
    {"id": "H41", "name": "Melodic Minor"},
    {"id": "H42", "name": "Double Harmonic"},
    {"id": "H43", "name": "Drop-2 voicing"},
    {"id": "H44", "name": "Open voicing"},
    {"id": "H45", "name": "Closed voicing"},
    {"id": "H46", "name": "Block chords"},
    {"id": "H47", "name": "Arpeggiated"},
    {"id": "H48", "name": "Ostinato"},
    {"id": "H49", "name": "Riff-based"},
    {"id": "H50", "name": "Unison"},
    {"id": "H51", "name": "Counterpoint"},
    {"id": "H52", "name": "Polytonality"},
    {"id": "H53", "name": "Atonal"},
    {"id": "H54", "name": "Microtonal"},
    {"id": "H55", "name": "Just Intonation"},
    {"id": "H56", "name": "Pythagorean tuning"},
    {"id": "H57", "name": "Quarter-tone"},
    {"id": "H58", "name": "Blue notes"},
    {"id": "H59", "name": "Line cliché"},
    {"id": "H60", "name": "Walk-down"},
    {"id": "H61", "name": "Walk-up"},
    {"id": "H62", "name": "Turnaround"},
    {"id": "H63", "name": "Vamp"},
    {"id": "H64", "name": "Cadence Plagal"}
    ]
    },
    {
    "id": "L4",
    "name": "Vocal Phonetics",
    "markers": [
    {"id": "P1", "name": "/æ/ cat"},
    {"id": "P2", "name": "/i/ see"},
    {"id": "P3", "name": "/u/ moon"},
    {"id": "P4", "name": "/ɑ/ father"},
    {"id": "P5", "name": "/ɔ/ thought"},
    {"id": "P6", "name": "/ɛ/ bed"},
    {"id": "P7", "name": "Diphthong /aɪ/"},
    {"id": "P8", "name": "Diphthong /aʊ/"},
    {"id": "P9", "name": "Glottal stop"},
    {"id": "P10", "name": "Vocal fry"},
    {"id": "P11", "name": "Breathiness"},
    {"id": "P12", "name": "Nasality"},
    {"id": "P13", "name": "Vibrato slow"},
    {"id": "P14", "name": "Vibrato fast"},
    {"id": "P15", "name": "Scoop up"},
    {"id": "P16", "name": "Fall off"},
    {"id": "P17", "name": "Yodel"},
    {"id": "P18", "name": "Whistle register"},
    {"id": "P19", "name": "Growl"},
    {"id": "P20", "name": "Scream"},
    {"id": "P21", "name": "Rap flow triplet"},
    {"id": "P22", "name": "Rap flow double-time"},
    {"id": "P23", "name": "Melisma"},
    {"id": "P24", "name": "Scat singing"},
    {"id": "P25", "name": "Spoken word"},
    {"id": "P26", "name": "Chant"},
    {"id": "P27", "name": "Choir SATB"},
    {"id": "P28", "name": "Gang vocals"},
    {"id": "P29", "name": "Whisper"},
    {"id": "P30", "name": "Falsetto"},
    {"id": "P31", "name": "Chest voice"},
    {"id": "P32", "name": "Mixed voice"},
    {"id": "P33", "name": "Belting"},
    {"id": "P34", "name": "Twang"},
    {"id": "P35", "name": "Sobbing"},
    {"id": "P36", "name": "Laughing"},
    {"id": "P37", "name": "Sibilance harsh"},
    {"id": "P38", "name": "Plosive hard"},
    {"id": "P39", "name": "De-essed"},
    {"id": "P40", "name": "Auto-Tune Hard"},
    {"id": "P41", "name": "Auto-Tune Natural"},
    {"id": "P42", "name": "Melodyne Artifacts"},
    {"id": "P43", "name": "Vocoder Robot"},
    {"id": "P44", "name": "Talkbox Tube"},
    {"id": "P45", "name": "Formant Shift Up"},
    {"id": "P46", "name": "Formant Shift Down"},
    {"id": "P47", "name": "Harmonizer 3rd"},
    {"id": "P48", "name": "Harmonizer 5th"},
    {"id": "P49", "name": "Octave doubler"},
    {"id": "P50", "name": "Double tracking"},
    {"id": "P51", "name": "Ad-libs"},
    {"id": "P52", "name": "Beatbox"},
    {"id": "P53", "name": "Lip trill"},
    {"id": "P54", "name": "Tongue trill"},
    {"id": "P55", "name": "Throat singing"},
    {"id": "P56", "name": "Overtone singing"},
    {"id": "P57", "name": "Death growl"},
    {"id": "P58", "name": "Pig squeal"},
    {"id": "P59", "name": "Inhale scream"},
    {"id": "P60", "name": "Speech sample"},
    {"id": "P61", "name": "Radio filter"},
    {"id": "P62", "name": "Telephone filter"},
    {"id": "P63", "name": "Megaphone"},
    {"id": "P64", "name": "Reverse vocal"}
    ]
    },
    {
    "id": "L5",
    "name": "Drum Genome",
    "markers": [
    {"id": "D1", "name": "Kick tight"},
    {"id": "D2", "name": "Kick boomy"},
    {"id": "D3", "name": "Snare rattling"},
    {"id": "D4", "name": "Snare dry"},
    {"id": "D5", "name": "Tom floor"},
    {"id": "D6", "name": "Tom rack"},
    {"id": "D7", "name": "Hi-hat tight"},
    {"id": "D8", "name": "Hi-hat slushy"},
    {"id": "D9", "name": "Ride dark"},
    {"id": "D10", "name": "Ride bright"},
    {"id": "D11", "name": "Crash explosive"},
    {"id": "D12", "name": "Crash fast decay"},
    {"id": "D13", "name": "China trashy"},
    {"id": "D14", "name": "Splash fast"},
    {"id": "D15", "name": "Electronic 808"},
    {"id": "D16", "name": "Electronic 909"},
    {"id": "D17", "name": "LinnDrum"},
    {"id": "D18", "name": "DMX drum"},
    {"id": "D19", "name": "Sampled break"},
    {"id": "D20", "name": "Lo-fi kit"},
    {"id": "D21", "name": "Brush swirl"},
    {"id": "D22", "name": "Brush hit"},
    {"id": "D23", "name": "Mallet swell"},
    {"id": "D24", "name": "Mallet hit"},
    {"id": "D25", "name": "Hand percussion"},
    {"id": "D26", "name": "Programmed roll"},
    {"id": "D27", "name": "Human roll"},
    {"id": "D28", "name": "Velocity max"},
    {"id": "D29", "name": "Velocity min"},
    {"id": "D30", "name": "Double pedal"},
    {"id": "D31", "name": "Linear drumming"},
    {"id": "D32", "name": "Open-handed"},
    {"id": "D33", "name": "FM Percussion"},
    {"id": "D34", "name": "Granular snare"},
    {"id": "D35", "name": "Wavetable kick"},
    {"id": "D36", "name": "Resonant zap"},
    {"id": "D37", "name": "Noise burst"},
    {"id": "D38", "name": "Glitch click"},
    {"id": "D39", "name": "Bitcrushed hits"},
    {"id": "D40", "name": "Gated reverb snare"},
    {"id": "D41", "name": "Reverse cymbal"},
    {"id": "D42", "name": "Reverse snare"},
    {"id": "D43", "name": "Tape stop kick"},
    {"id": "D44", "name": "Filter sweep hat"},
    {"id": "D45", "name": "Flanged drum fill"},
    {"id": "D46", "name": "Phased overheads"},
    {"id": "D47", "name": "Distorted 808"},
    {"id": "D48", "name": "Clipped kick"},
    {"id": "D49", "name": "Transient shaped"},
    {"id": "D50", "name": "Layered Clap/Snare"},
    {"id": "D51", "name": "Layered Kick/Sub"},
    {"id": "D52", "name": "Hydraulic press"},
    {"id": "D53", "name": "Industrial clang"},
    {"id": "D54", "name": "Glass break"},
    {"id": "D55", "name": "Gunshot"},
    {"id": "D56", "name": "Foley percussion"},
    {"id": "D57", "name": "Water splash"},
    {"id": "D58", "name": "Metallic scrape"},
    {"id": "D59", "name": "Wood hit"},
    {"id": "D60", "name": "Plastic hit"},
    {"id": "D61", "name": "Body percussion"},
    {"id": "D62", "name": "Stomp"},
    {"id": "D63", "name": "Snap reverb"},
    {"id": "D64", "name": "Finger drum"}
    ]
    },
    {
    "id": "L6",
    "name": "Bass Genome",
    "markers": [
    {"id": "B1", "name": "Pick attack"},
    {"id": "B2", "name": "Finger pluck"},
    {"id": "B3", "name": "Thumb slap"},
    {"id": "B4", "name": "Pop pull"},
    {"id": "B5", "name": "Palm mute"},
    {"id": "B6", "name": "Ghost note"},
    {"id": "B7", "name": "Hammer-on"},
    {"id": "B8", "name": "Pull-off"},
    {"id": "B9", "name": "Slide up"},
    {"id": "B10", "name": "Slide down"},
    {"id": "B11", "name": "String buzz"},
    {"id": "B12", "name": "Fret noise"},
    {"id": "B13", "name": "Harmonics"},
    {"id": "B14", "name": "Tapping"},
    {"id": "B15", "name": "Chords"},
    {"id": "B16", "name": "Double stops"},
    {"id": "B17", "name": "Upright pizz"},
    {"id": "B18", "name": "Upright arco"},
    {"id": "B19", "name": "Upright slap"},
    {"id": "B20", "name": "Synth sine"},
    {"id": "B21", "name": "Synth saw"},
    {"id": "B22", "name": "Synth square"},
    {"id": "B23", "name": "Synth pulse"},
    {"id": "B24", "name": "Synth triangle"},
    {"id": "B25", "name": "Sub-bass"},
    {"id": "B26", "name": "Wobble bass"},
    {"id": "B27", "name": "Reese bass"},
    {"id": "B28", "name": "Acid bass 303"},
    {"id": "B29", "name": "Donk bass"},
    {"id": "B30", "name": "Pluck bass"},
    {"id": "B31", "name": "Pad bass"},
    {"id": "B32", "name": "Drone bass"},
    {"id": "B33", "name": "Fuzz bass"},
    {"id": "B34", "name": "Distortion bass"},
    {"id": "B35", "name": "Overdrive bass"},
    {"id": "B36", "name": "Bitcrush bass"},
    {"id": "B37", "name": "Envelope filter"},
    {"id": "B38", "name": "Wah bass"},
    {"id": "B39", "name": "Chorus bass"},
    {"id": "B40", "name": "Flanger bass"},
    {"id": "B41", "name": "Phaser bass"},
    {"id": "B42", "name": "Octaver down"},
    {"id": "B43", "name": "Octaver up"},
    {"id": "B44", "name": "Synth glissando"},
    {"id": "B45", "name": "Sidechain pump"},
    {"id": "B46", "name": "Gated fuzz"},
    {"id": "B47", "name": "Bass drop"},
    {"id": "B48", "name": "808 distort"},
    {"id": "B49", "name": "808 clean"},
    {"id": "B50", "name": "808 slide"},
    {"id": "B51", "name": "Neuro bass"},
    {"id": "B52", "name": "Growl bass"},
    {"id": "B53", "name": "Talk bass"},
    {"id": "B54", "name": "FM bass"},
    {"id": "B55", "name": "Organ pedals"},
    {"id": "B56", "name": "Tuba line"},
    {"id": "B57", "name": "Sousaphone"},
    {"id": "B58", "name": "Bassoon"},
    {"id": "B59", "name": "Contrabass clarinet"},
    {"id": "B60", "name": "Baritone sax"},
    {"id": "B61", "name": "Cello section"},
    {"id": "B62", "name": "Double bass section"},
    {"id": "B63", "name": "Bass harp"},
    {"id": "B64", "name": "Piano low octave"}
    ]
    },
    {
    "id": "L7",
    "name": "FX Chain",
    "markers": [
    {"id": "F1", "name": "Reverb Hall"},
    {"id": "F2", "name": "Reverb Room"},
    {"id": "F3", "name": "Reverb Plate"},
    {"id": "F4", "name": "Reverb Spring"},
    {"id": "F5", "name": "Reverb Chamber"},
    {"id": "F6", "name": "Reverb Ambience"},
    {"id": "F7", "name": "Reverb Non-lin"},
    {"id": "F8", "name": "Reverb Shimmer"},
    {"id": "F9", "name": "Delay Slapback"},
    {"id": "F10", "name": "Delay Tape"},
    {"id": "F11", "name": "Delay Digital"},
    {"id": "F12", "name": "Delay Analog"},
    {"id": "F13", "name": "Delay Ping-pong"},
    {"id": "F14", "name": "Delay Multi-tap"},
    {"id": "F15", "name": "Delay Reverse"},
    {"id": "F16", "name": "Delay Grain"},
    {"id": "F17", "name": "Chorus mono"},
    {"id": "F18", "name": "Chorus stereo"},
    {"id": "F19", "name": "Flanger jet"},
    {"id": "F20", "name": "Flanger metallic"},
    {"id": "F21", "name": "Phaser 4-stage"},
    {"id": "F22", "name": "Phaser 12-stage"},
    {"id": "F23", "name": "Tremolo optical"},
    {"id": "F24", "name": "Tremolo bias"},
    {"id": "F25", "name": "Vibrato"},
    {"id": "F26", "name": "Rotary speaker"},
    {"id": "F27", "name": "Uni-Vibe"},
    {"id": "F28", "name": "Ring Modulator"},
    {"id": "F29", "name": "Frequency Shifter"},
    {"id": "F30", "name": "Pitch Shifter"},
    {"id": "F31", "name": "Whammy pedal"},
    {"id": "F32", "name": "Harmonizer"},
    {"id": "F33", "name": "Distortion Tube"},
    {"id": "F34", "name": "Distortion Diode"},
    {"id": "F35", "name": "Fuzz Silicon"},
    {"id": "F36", "name": "Fuzz Germanium"},
    {"id": "F37", "name": "Bitcrusher"},
    {"id": "F38", "name": "Sample Rate Reducer"},
    {"id": "F39", "name": "Waveshaper"},
    {"id": "F40", "name": "Exciter"},
    {"id": "F41", "name": "Enhancer"},
    {"id": "F42", "name": "Stereo Widener"},
    {"id": "F43", "name": "Compressor VCA"},
    {"id": "F44", "name": "Compressor FET"},
    {"id": "F45", "name": "Compressor Opto"},
    {"id": "F46", "name": "Compressor Tube"},
    {"id": "F47", "name": "Limiter Brickwall"},
    {"id": "F48", "name": "Limiter Soft"},
    {"id": "F49", "name": "Gate Hard"},
    {"id": "F50", "name": "Gate Soft"},
    {"id": "F51", "name": "Transient Shaper"},
    {"id": "F52", "name": "De-esser"},
    {"id": "F53", "name": "EQ Low-pass"},
    {"id": "F54", "name": "EQ High-pass"},
    {"id": "F55", "name": "EQ Band-pass"},
    {"id": "F56", "name": "EQ Notch"},
    {"id": "F57", "name": "Telephone EQ"},
    {"id": "F58", "name": "Megaphone EQ"},
    {"id": "F59", "name": "Vinyl Sim"},
    {"id": "F60", "name": "Tape Sim"},
    {"id": "F61", "name": "Cassette Sim"},
    {"id": "F62", "name": "Glitch Stutter"},
    {"id": "F63", "name": "Granular Cloud"},
    {"id": "F64", "name": "Convolution Impulse"}
    ]
    },
    {
    "id": "L8",
    "name": "Arrangement",
    "markers": [
    {"id": "A1", "name": "Intro"},
    {"id": "A2", "name": "Verse 1"},
    {"id": "A3", "name": "Verse 2"},
    {"id": "A4", "name": "Verse 3"},
    {"id": "A5", "name": "Pre-Chorus"},
    {"id": "A6", "name": "Chorus 1"},
    {"id": "A7", "name": "Chorus 2"},
    {"id": "A8", "name": "Chorus 3"},
    {"id": "A9", "name": "Bridge"},
    {"id": "A10", "name": "Solo Guitar"},
    {"id": "A11", "name": "Solo Synth"},
    {"id": "A12", "name": "Solo Other"},
    {"id": "A13", "name": "Interlude"},
    {"id": "A14", "name": "Breakdown"},
    {"id": "A15", "name": "Build-up"},
    {"id": "A16", "name": "Drop"},
    {"id": "A17", "name": "Outro"},
    {"id": "A18", "name": "Fade Out"},
    {"id": "A19", "name": "Cold End"},
    {"id": "A20", "name": "Sustain End"},
    {"id": "A21", "name": "False Ending"},
    {"id": "A22", "name": "Hook Instrumental"},
    {"id": "A23", "name": "Hook Vocal"},
    {"id": "A24", "name": "Post-Chorus"},
    {"id": "A25", "name": "Tag"},
    {"id": "A26", "name": "Vamp"},
    {"id": "A27", "name": "A Cappella"},
    {"id": "A28", "name": "Instrumental Break"},
    {"id": "A29", "name": "Drum Break"},
    {"id": "A30", "name": "Bass Break"},
    {"id": "A31", "name": "Silence"},
    {"id": "A32", "name": "Count-in"},
    {"id": "A33", "name": "Texture Sparse"},
    {"id": "A34", "name": "Texture Medium"},
    {"id": "A35", "name": "Texture Dense"},
    {"id": "A36", "name": "Wall of Sound"},
    {"id": "A37", "name": "Minimal"},
    {"id": "A38", "name": "Looped structure"},
    {"id": "A39", "name": "Through-composed"},
    {"id": "A40", "name": "Strophic"},
    {"id": "A41", "name": "12-Bar Blues"},
    {"id": "A42", "name": "AABA"},
    {"id": "A43", "name": "Ternary ABA"},
    {"id": "A44", "name": "Rondo ABACA"},
    {"id": "A45", "name": "Theme and Variations"},
    {"id": "A46", "name": "Call and Response"},
    {"id": "A47", "name": "Unison section"},
    {"id": "A48", "name": "Harmony section"},
    {"id": "A49", "name": "Counterpoint section"},
    {"id": "A50", "name": "Key Change Up"},
    {"id": "A51", "name": "Key Change Down"},
    {"id": "A52", "name": "Tempo Accel"},
    {"id": "A53", "name": "Tempo Ritard"},
    {"id": "A54", "name": "Double Time"},
    {"id": "A55", "name": "Half Time"},
    {"id": "A56", "name": "Stop-time"},
    {"id": "A57", "name": "Rubato"},
    {"id": "A58", "name": "Fermata"},
    {"id": "A59", "name": "Attacca"},
    {"id": "A60", "name": "Segue"},
    {"id": "A61", "name": "Crossfade"},
    {"id": "A62", "name": "Hard cut"},
    {"id": "A63", "name": "Layer Add"},
    {"id": "A64", "name": "Layer Subtract"}
    ]
    },
    {
    "id": "L9",
    "name": "Emotional Cues",
    "markers": [
    {"id": "E1", "name": "Joy"},
    {"id": "E2", "name": "Sadness"},
    {"id": "E3", "name": "Anger"},
    {"id": "E4", "name": "Fear"},
    {"id": "E5", "name": "Surprise"},
    {"id": "E6", "name": "Disgust"},
    {"id": "E7", "name": "Trust"},
    {"id": "E8", "name": "Anticipation"},
    {"id": "E9", "name": "Love"},
    {"id": "E10", "name": "Hate"},
    {"id": "E11", "name": "Nostalgia"},
    {"id": "E12", "name": "Hope"},
    {"id": "E13", "name": "Despair"},
    {"id": "E14", "name": "Triumph"},
    {"id": "E15", "name": "Defeat"},
    {"id": "E16", "name": "Calm"},
    {"id": "E17", "name": "Excitement"},
    {"id": "E18", "name": "Tension"},
    {"id": "E19", "name": "Release"},
    {"id": "E20", "name": "Confusion"},
    {"id": "E21", "name": "Clarity"},
    {"id": "E22", "name": "Ethereal"},
    {"id": "E23", "name": "Grounded"},
    {"id": "E24", "name": "Spiritual"},
    {"id": "E25", "name": "Aggressive"},
    {"id": "E26", "name": "Passive"},
    {"id": "E27", "name": "Dark"},
    {"id": "E28", "name": "Bright"},
    {"id": "E29", "name": "Warm"},
    {"id": "E30", "name": "Cold"},
    {"id": "E31", "name": "Heavy"},
    {"id": "E32", "name": "Light"},
    {"id": "E33", "name": "Urgent"},
    {"id": "E34", "name": "Lazy"},
    {"id": "E35", "name": "Serious"},
    {"id": "E36", "name": "Playful"},
    {"id": "E37", "name": "Sarcastic"},
    {"id": "E38", "name": "Sincere"},
    {"id": "E39", "name": "Romantic"},
    {"id": "E40", "name": "Platonic"},
    {"id": "E41", "name": "Sexual"},
    {"id": "E42", "name": "Innocent"},
    {"id": "E43", "name": "Groovy"},
    {"id": "E44", "name": "Stiff"},
    {"id": "E45", "name": "Robotic"},
    {"id": "E46", "name": "Human"},
    {"id": "E47", "name": "Dreamy"},
    {"id": "E48", "name": "Nightmarish"},
    {"id": "E49", "name": "Heroic"},
    {"id": "E50", "name": "Villainous"},
    {"id": "E51", "name": "Psychedelic"},
    {"id": "E52", "name": "Sober"},
    {"id": "E53", "name": "Chaotic"},
    {"id": "E54", "name": "Ordered"},
    {"id": "E55", "name": "Minimalist"},
    {"id": "E56", "name": "Bombastic"},
    {"id": "E57", "name": "Intimate"},
    {"id": "E58", "name": "Epic"},
    {"id": "E59", "name": "Melancholic"},
    {"id": "E60", "name": "Euphoric"},
    {"id": "E61", "name": "Anxious"},
    {"id": "E62", "name": "Confident"},
    {"id": "E63", "name": "Lonely"},
    {"id": "E64", "name": "Crowded"}
    ]
    },
    {
    "id": "L10",
    "name": "Cultural Markers",
    "markers": [
    {"id": "C1", "name": "Western Pop"},
    {"id": "C2", "name": "Western Rock"},
    {"id": "C3", "name": "Western Jazz"},
    {"id": "C4", "name": "Western Classical"},
    {"id": "C5", "name": "African Rhythm"},
    {"id": "C6", "name": "Latin Percussion"},
    {"id": "C7", "name": "Caribbean Steel"},
    {"id": "C8", "name": "Indian Raga"},
    {"id": "C9", "name": "Indian Drone"},
    {"id": "C10", "name": "Arabic Maqam"},
    {"id": "C11", "name": "Arabic Strings"},
    {"id": "C12", "name": "Asian Pentatonic"},
    {"id": "C13", "name": "Japanese Koto"},
    {"id": "C14", "name": "Chinese Erhu"},
    {"id": "C15", "name": "Gamelan"},
    {"id": "C16", "name": "Celtic Folk"},
    {"id": "C17", "name": "Nordic Folk"},
    {"id": "C18", "name": "Eastern Euro Folk"},
    {"id": "C19", "name": "Polka"},
    {"id": "C20", "name": "Waltz"},
    {"id": "C21", "name": "Tango"},
    {"id": "C22", "name": "Bossa Nova"},
    {"id": "C23", "name": "Samba"},
    {"id": "C24", "name": "Salsa"},
    {"id": "C25", "name": "Reggae"},
    {"id": "C26", "name": "Dub"},
    {"id": "C27", "name": "Afrobeat"},
    {"id": "C28", "name": "Highlife"},
    {"id": "C29", "name": "K-Pop"},
    {"id": "C30", "name": "J-Pop"},
    {"id": "C31", "name": "Bollywood"},
    {"id": "C32", "name": "Americana"},
    {"id": "C33", "name": "Blues Delta"},
    {"id": "C34", "name": "Blues Chicago"},
    {"id": "C35", "name": "Country Trad"},
    {"id": "C36", "name": "Country Modern"},
    {"id": "C37", "name": "Bluegrass"},
    {"id": "C38", "name": "Gospel"},
    {"id": "C39", "name": "Soul Motown"},
    {"id": "C40", "name": "Soul Stax"},
    {"id": "C41", "name": "Funk P-Funk"},
    {"id": "C42", "name": "Disco"},
    {"id": "C43", "name": "Hip-Hop East"},
    {"id": "C44", "name": "Hip-Hop West"},
    {"id": "C45", "name": "Hip-Hop Trap"},
    {"id": "C46", "name": "Electronic House"},
    {"id": "C47", "name": "Electronic Techno"},
    {"id": "C48", "name": "Electronic Trance"},
    {"id": "C49", "name": "Electronic DnB"},
    {"id": "C50", "name": "Electronic Dubstep"},
    {"id": "C51", "name": "Metal Heavy"},
    {"id": "C52", "name": "Metal Thrash"},
    {"id": "C53", "name": "Metal Death"},
    {"id": "C54", "name": "Metal Black"},
    {"id": "C55", "name": "Punk 70s"},
    {"id": "C56", "name": "Punk Hardcore"},
    {"id": "C57", "name": "Grunge"},
    {"id": "C58", "name": "Shoegaze"},
    {"id": "C59", "name": "Post-Rock"},
    {"id": "C60", "name": "Ambient"},
    {"id": "C61", "name": "Noise"},
    {"id": "C62", "name": "Experimental"},
    {"id": "C63", "name": "Avant-Garde"},
    {"id": "C64", "name": "Musique Concrète"}
    ]
    },
    {
    "id": "L11",
    "name": "Historical Era",
    "markers": [
    {"id": "HE1", "name": "Pre-1950"},
    {"id": "HE2", "name": "1950-1954"},
    {"id": "HE3", "name": "1955-1959"},
    {"id": "HE4", "name": "1960-1964"},
    {"id": "HE5", "name": "1965-1969"},
    {"id": "HE6", "name": "1970-1974"},
    {"id": "HE7", "name": "1975-1979"},
    {"id": "HE8", "name": "1980-1984"},
    {"id": "HE9", "name": "1985-1989"},
    {"id": "HE10", "name": "1990-1994"},
    {"id": "HE11", "name": "1995-1999"},
    {"id": "HE12", "name": "2000-2004"},
    {"id": "HE13", "name": "2005-2009"},
    {"id": "HE14", "name": "2010-2014"},
    {"id": "HE15", "name": "2015-2019"},
    {"id": "HE16", "name": "2020-Present"},
    {"id": "HE17", "name": "Era Ambiguous"},
    {"id": "HE18", "name": "Retro 50s"},
    {"id": "HE19", "name": "Retro 60s"},
    {"id": "HE20", "name": "Retro 70s"},
    {"id": "HE21", "name": "Retro 80s"},
    {"id": "HE22", "name": "Retro 90s"},
    {"id": "HE23", "name": "Futuristic"},
    {"id": "HE24", "name": "Production Lo-Fi"},
    {"id": "HE25", "name": "Production Hi-Fi"},
    {"id": "HE26", "name": "Production Bedroom"},
    {"id": "HE27", "name": "Production Studio"},
    {"id": "HE28", "name": "Production Live"},
    {"id": "HE29", "name": "Mastering Quiet"},
    {"id": "HE30", "name": "Mastering Loud"},
    {"id": "HE31", "name": "Analog Format"},
    {"id": "HE32", "name": "Digital Format"}
    ]
    },
    {
    "id": "L12",
    "name": "Melodic Contour",
    "markers": [
    {"id": "M1", "name": "Stepwise Up"},
    {"id": "M2", "name": "Stepwise Down"},
    {"id": "M3", "name": "Skip Up 3rd"},
    {"id": "M4", "name": "Skip Down 3rd"},
    {"id": "M5", "name": "Leap Up 4th"},
    {"id": "M6", "name": "Leap Down 4th"},
    {"id": "M7", "name": "Leap Up 5th"},
    {"id": "M8", "name": "Leap Down 5th"},
    {"id": "M9", "name": "Leap Up Wide"},
    {"id": "M10", "name": "Leap Down Wide"},
    {"id": "M11", "name": "Octave Jump Up"},
    {"id": "M12", "name": "Octave Jump Down"},
    {"id": "M13", "name": "Repeated Note"},
    {"id": "M14", "name": "Trill"},
    {"id": "M15", "name": "Turn"},
    {"id": "M16", "name": "Appoggiatura"},
    {"id": "M17", "name": "Acciaccatura"},
    {"id": "M18", "name": "Mordent"},
    {"id": "M19", "name": "Glissando Up"},
    {"id": "M20", "name": "Glissando Down"},
    {"id": "M21", "name": "Portamento"},
    {"id": "M22", "name": "Arch Contour"},
    {"id": "M23", "name": "Inv-Arch Contour"},
    {"id": "M24", "name": "Rising Line"},
    {"id": "M25", "name": "Falling Line"},
    {"id": "M26", "name": "Wave Contour"},
    {"id": "M27", "name": "Static Contour"},
    {"id": "M28", "name": "Erratic Contour"},
    {"id": "M29", "name": "Range Narrow"},
    {"id": "M30", "name": "Range Medium"},
    {"id": "M31", "name": "Range Wide"},
    {"id": "M32", "name": "Register Low"},
    {"id": "M33", "name": "Register Mid"},
    {"id": "M34", "name": "Register High"},
    {"id": "M35", "name": "Register Extreme"},
    {"id": "M36", "name": "Tessitura Steady"},
    {"id": "M37", "name": "Tessitura Shifting"},
    {"id": "M38", "name": "Phrasing Short"},
    {"id": "M39", "name": "Phrasing Long"},
    {"id": "M40", "name": "Phrasing Irregular"},
    {"id": "M41", "name": "Motif Repetition"},
    {"id": "M42", "name": "Sequence Up"},
    {"id": "M43", "name": "Sequence Down"},
    {"id": "M44", "name": "Inversion"},
    {"id": "M45", "name": "Retrograde"},
    {"id": "M46", "name": "Augmentation"},
    {"id": "M47", "name": "Diminution"},
    {"id": "M48", "name": "Call-Response"}
    ]
    },
    {
    "id": "L13",
    "name": "Rhythmic Hierarchy",
    "markers": [
    {"id": "RH1", "name": "BPM < 60"},
    {"id": "RH2", "name": "BPM 60-80"},
    {"id": "RH3", "name": "BPM 80-100"},
    {"id": "RH4", "name": "BPM 100-120"},
    {"id": "RH5", "name": "BPM 120-140"},
    {"id": "RH6", "name": "BPM 140-160"},
    {"id": "RH7", "name": "BPM 160-180"},
    {"id": "RH8", "name": "BPM > 180"},
    {"id": "RH9", "name": "Meter 4/4"},
    {"id": "RH10", "name": "Meter 3/4"},
    {"id": "RH11", "name": "Meter 2/4"},
    {"id": "RH12", "name": "Meter 6/8"},
    {"id": "RH13", "name": "Meter 12/8"},
    {"id": "RH14", "name": "Meter 5/4"},
    {"id": "RH15", "name": "Meter 7/4"},
    {"id": "RH16", "name": "Meter 7/8"},
    {"id": "RH17", "name": "Meter 9/8"},
    {"id": "RH18", "name": "Meter Polymetric"},
    {"id": "RH19", "name": "Feel Straight"},
    {"id": "RH20", "name": "Feel Swing"},
    {"id": "RH21", "name": "Feel Shuffle"},
    {"id": "RH22", "name": "Feel Half-time"},
    {"id": "RH23", "name": "Feel Double-time"},
    {"id": "RH24", "name": "Feel Cut-time"},
    {"id": "RH25", "name": "Subdiv Quarter"},
    {"id": "RH26", "name": "Subdiv 8th"},
    {"id": "RH27", "name": "Subdiv 16th"},
    {"id": "RH28", "name": "Subdiv 32nd"},
    {"id": "RH29", "name": "Triplet Quarter"},
    {"id": "RH30", "name": "Triplet 8th"},
    {"id": "RH31", "name": "Triplet 16th"},
    {"id": "RH32", "name": "Quintuplets"},
    {"id": "RH33", "name": "Septuplets"},
    {"id": "RH34", "name": "Syncopation Low"},
    {"id": "RH35", "name": "Syncopation Med"},
    {"id": "RH36", "name": "Syncopation High"},
    {"id": "RH37", "name": "Downbeat Strong"},
    {"id": "RH38", "name": "Downbeat Weak"},
    {"id": "RH39", "name": "Backbeat Strong"},
    {"id": "RH40", "name": "Backbeat Weak"},
    {"id": "RH41", "name": "Pickup Note"},
    {"id": "RH42", "name": "Anticipation"},
    {"id": "RH43", "name": "Delay"},
    {"id": "RH44", "name": "Rubato"},
    {"id": "RH45", "name": "Accelerando"},
    {"id": "RH46", "name": "Ritardando"},
    {"id": "RH47", "name": "Fermata"},
    {"id": "RH48", "name": "Polyrhythm 3:2"},
    {"id": "RH49", "name": "Polyrhythm 4:3"},
    {"id": "RH50", "name": "Polyrhythm 5:4"},
    {"id": "RH51", "name": "Hemiola"},
    {"id": "RH52", "name": "Metric Modulation"},
    {"id": "RH53", "name": "Euclidean Rhythm"},
    {"id": "RH54", "name": "Clave Son"},
    {"id": "RH55", "name": "Clave Rumba"},
    {"id": "RH56", "name": "Clave Bossa"},
    {"id": "RH57", "name": "Tresillo"},
    {"id": "RH58", "name": "Cinquillo"},
    {"id": "RH59", "name": "Dem Bow"},
    {"id": "RH60", "name": "One Drop"},
    {"id": "RH61", "name": "Steppers"},
    {"id": "RH62", "name": "Rockers"},
    {"id": "RH63", "name": "Motorik"},
    {"id": "RH64", "name": "Four-on-floor"}
    ]
    },
    {
    "id": "L14",
    "name": "Source Separation",
    "markers": [
    {"id": "SS1", "name": "Vocal Conf >90%"},
    {"id": "SS2", "name": "Vocal Conf >70%"},
    {"id": "SS3", "name": "Vocal Conf >50%"},
    {"id": "SS4", "name": "Vocal Absent"},
    {"id": "SS5", "name": "Drums Conf >90%"},
    {"id": "SS6", "name": "Drums Conf >70%"},
    {"id": "SS7", "name": "Drums Conf >50%"},
    {"id": "SS8", "name": "Drums Absent"},
    {"id": "SS9", "name": "Bass Conf >90%"},
    {"id": "SS10", "name": "Bass Conf >70%"},
    {"id": "SS11", "name": "Bass Conf >50%"},
    {"id": "SS12", "name": "Bass Absent"},
    {"id": "SS13", "name": "Other Conf >90%"},
    {"id": "SS14", "name": "Other Conf >70%"},
    {"id": "SS15", "name": "Other Conf >50%"},
    {"id": "SS16", "name": "Other Absent"},
    {"id": "SS17", "name": "Piano Detect"},
    {"id": "SS18", "name": "Guitar Detect"},
    {"id": "SS19", "name": "Synth Detect"},
    {"id": "SS20", "name": "Strings Detect"},
    {"id": "SS21", "name": "Brass Detect"},
    {"id": "SS22", "name": "Wind Detect"},
    {"id": "SS23", "name": "Vocal Bleed Low"},
    {"id": "SS24", "name": "Vocal Bleed High"},
    {"id": "SS25", "name": "Drum Bleed Low"},
    {"id": "SS26", "name": "Drum Bleed High"},
    {"id": "SS27", "name": "Artifacts Phasing"},
    {"id": "SS28", "name": "Artifacts Musical"},
    {"id": "SS29", "name": "Artifacts Noise"},
    {"id": "SS30", "name": "Stereo Imbalance"},
    {"id": "SS31", "name": "Mono Source"},
    {"id": "SS32", "name": "Separation Clean"}
    ]
    },
    {
    "id": "L15",
    "name": "Instrument Specifics",
    "markers": [
    {"id": "IS1-IS32", "name": "Guitar Types"},
    {"id": "IS33-IS64", "name": "Guitar Amps"},
    {"id": "IS65-IS96", "name": "Keys Acoustic"},
    {"id": "IS97-IS128", "name": "Keys Electric"},
    {"id": "IS129-IS160", "name": "Synths"},
    {"id": "IS161-IS192", "name": "Strings"},
    {"id": "IS193-IS224", "name": "Brass/Winds"},
    {"id": "IS225-IS256", "name": "World Instruments"}
    ]
    },
    {
    "id": "L16",
    "name": "Groove & Microtiming",
    "markers": [
    {"id": "G1", "name": "Grid Quantized"},
    {"id": "G2", "name": "Human Tight"},
    {"id": "G3", "name": "Human Loose"},
    {"id": "G4", "name": "Sloppy"},
    {"id": "G5", "name": "Swing 51-55%"},
    {"id": "G6", "name": "Swing 56-60%"},
    {"id": "G7", "name": "Swing 61-65%"},
    {"id": "G8", "name": "Swing 66-70%"},
    {"id": "G9", "name": "Swing >70%"},
    {"id": "G10", "name": "Push <10ms"},
    {"id": "G11", "name": "Push 10-20ms"},
    {"id": "G12", "name": "Push 20-30ms"},
    {"id": "G13", "name": "Push >30ms"},
    {"id": "G14", "name": "Drag <10ms"},
    {"id": "G15", "name": "Drag 10-20ms"},
    {"id": "G16", "name": "Drag 20-30ms"},
    {"id": "G17", "name": "Drag >30ms"},
    {"id": "G18", "name": "Kick Ahead"},
    {"id": "G19", "name": "Kick Behind"},
    {"id": "G20", "name": "Snare Ahead"},
    {"id": "G21", "name": "Snare Behind"},
    {"id": "G22", "name": "Hat Ahead"},
    {"id": "G23", "name": "Hat Behind"},
    {"id": "G24", "name": "Bass Ahead"},
    {"id": "G25", "name": "Bass Behind"},
    {"id": "G26", "name": "Bass Locked"},
    {"id": "G27", "name": "Guitar Ahead"},
    {"id": "G28", "name": "Guitar Behind"},
    {"id": "G29", "name": "Keys Ahead"},
    {"id": "G30", "name": "Keys Behind"},
    {"id": "G31", "name": "Vocal Ahead"},
    {"id": "G32", "name": "Vocal Behind"},
    {"id": "G33", "name": "Pocket Deep"},
    {"id": "G34", "name": "Pocket Shallow"},
    {"id": "G35", "name": "Drunk Feel"},
    {"id": "G36", "name": "Machine Feel"},
    {"id": "G37", "name": "Rushing Fills"},
    {"id": "G38", "name": "Dragging Fills"},
    {"id": "G39", "name": "Tempo Drift Up"},
    {"id": "G40", "name": "Tempo Drift Down"},
    {"id": "G41", "name": "Tempo Stable"},
    {"id": "G42", "name": "Click Bleed"},
    {"id": "G43", "name": "Phase Locked"},
    {"id": "G44", "name": "Phase Drift"},
    {"id": "G45", "name": "Flamming"},
    {"id": "G46", "name": "Unison Tight"},
    {"id": "G47", "name": "Unison Loose"},
    {"id": "G48", "name": "Double Tight"},
    {"id": "G49", "name": "Double Loose"},
    {"id": "G50", "name": "Polyrhythmic Feel"},
    {"id": "G51", "name": "Metric Modulation"},
    {"id": "G52", "name": "Tuplet Swing"},
    {"id": "G53", "name": "Straight 8ths"},
    {"id": "G54", "name": "Straight 16ths"},
    {"id": "G55", "name": "Dotted 8ths"},
    {"id": "G56", "name": "Shuffle 8ths"},
    {"id": "G57", "name": "Shuffle 16ths"},
    {"id": "G58", "name": "Backbeat Delayed"},
    {"id": "G59", "name": "Backbeat Rushed"},
    {"id": "G60", "name": "One Delayed"},
    {"id": "G61", "name": "Syncopation Accel"},
    {"id": "G62", "name": "Syncopation Decel"},
    {"id": "G63", "name": "Groove Archetype A"},
    {"id": "G64", "name": "Groove Archetype B"}
    ]
    },
    {
    "id": "L17",
    "name": "Polyrhythm & Meter",
    "markers": [
    {"id": "PM1", "name": "Simple Duple"},
    {"id": "PM2", "name": "Simple Triple"},
    {"id": "PM3", "name": "Simple Quadruple"},
    {"id": "PM4", "name": "Compound Duple"},
    {"id": "PM5", "name": "Compound Triple"},
    {"id": "PM6", "name": "Compound Quadruple"},
    {"id": "PM7", "name": "Complex 5"},
    {"id": "PM8", "name": "Complex 7"},
    {"id": "PM9", "name": "Complex 9"},
    {"id": "PM10", "name": "Complex 11"},
    {"id": "PM11", "name": "Complex 13"},
    {"id": "PM12", "name": "Complex 15"},
    {"id": "PM13", "name": "Additive 3+2"},
    {"id": "PM14", "name": "Additive 2+3"},
    {"id": "PM15", "name": "Additive 3+3+2"},
    {"id": "PM16", "name": "Additive 2+2+3"},
    {"id": "PM17", "name": "Additive 4+3"},
    {"id": "PM18", "name": "Additive 3+4"},
    {"id": "PM19", "name": "Cross 3:2"},
    {"id": "PM20", "name": "Cross 2:3"},
    {"id": "PM21", "name": "Cross 4:3"},
    {"id": "PM22", "name": "Cross 3:4"},
    {"id": "PM23", "name": "Cross 5:4"},
    {"id": "PM24", "name": "Cross 4:5"},
    {"id": "PM25", "name": "Poly 3 vs 2"},
    {"id": "PM26", "name": "Poly 4 vs 3"},
    {"id": "PM27", "name": "Poly 5 vs 4"},
    {"id": "PM28", "name": "Poly 7 vs 4"},
    {"id": "PM29", "name": "Phasing"},
    {"id": "PM30", "name": "Displacement"},
    {"id": "PM31", "name": "Metric Mod Quarter=Dotted"},
    {"id": "PM32", "name": "Metric Mod Quarter=Triplet"},
    {"id": "PM33", "name": "Clave 2-3 Son"},
    {"id": "PM34", "name": "Clave 3-2 Son"},
    {"id": "PM35", "name": "Clave 2-3 Rumba"},
    {"id": "PM36", "name": "Clave 3-2 Rumba"},
    {"id": "PM37", "name": "Clave Bossa"},
    {"id": "PM38", "name": "Bell Pattern 12/8"},
    {"id": "PM39", "name": "Cascara"},
    {"id": "PM40", "name": "Tumbao"},
    {"id": "PM41", "name": "Martillo"},
    {"id": "PM42", "name": "Songo"},
    {"id": "PM43", "name": "Mozambique"},
    {"id": "PM44", "name": "Bembe"},
    {"id": "PM45", "name": "Abakua"},
    {"id": "PM46", "name": "Ijexá"},
    {"id": "PM47", "name": "Maracatu"},
    {"id": "PM48", "name": "Baiao"}
    ]
    },
    {
    "id": "L18",
    "name": "ML Latent Vectors",
    "markers": [
    {"id": "ML1", "name": "Latent Feature Vector"},
    {"id": "ML2", "name": "Vector Projection X"},
    {"id": "ML3", "name": "Vector Projection Y"}
    ]
    },
    {
    "id": "L20",
    "name": "Macro Structure",
    "markers": [
    {"id": "MS1", "name": "Intro Detected"},
    {"id": "MS2", "name": "Verse Detected"},
    {"id": "MS3", "name": "Chorus Detected"},
    {"id": "MS4", "name": "Bridge Detected"},
    {"id": "MS5", "name": "Outro Detected"},
    {"id": "MS6", "name": "Section Length Short"},
    {"id": "MS7", "name": "Section Length Med"},
    {"id": "MS8", "name": "Section Length Long"},
    {"id": "MS9", "name": "Complexity Rise"},
    {"id": "MS10", "name": "Complexity Fall"},
    {"id": "MS11", "name": "Energy Rise"},
    {"id": "MS12", "name": "Energy Fall"},
    {"id": "MS13", "name": "Timbre Change High"},
    {"id": "MS14", "name": "Timbre Change Low"},
    {"id": "MS15", "name": "Rhythm Change High"},
    {"id": "MS16", "name": "Rhythm Change Low"},
    {"id": "MS17", "name": "Key Change Detected"},
    {"id": "MS18", "name": "Tempo Change Detected"},
    {"id": "MS19", "name": "Meter Change Detected"},
    {"id": "MS20", "name": "Density High"},
    {"id": "MS21", "name": "Density Low"},
    {"id": "MS22", "name": "Repetition High"},
    {"id": "MS23", "name": "Repetition Low"},
    {"id": "MS24", "name": "Novelty High"},
    {"id": "MS25", "name": "Novelty Low"},
    {"id": "MS26", "name": "Transition Smooth"},
    {"id": "MS27", "name": "Transition Abrupt"},
    {"id": "MS28", "name": "Hook Strength"},
    {"id": "MS29", "name": "Catchiness Score"},
    {"id": "MS30", "name": "Danceability Score"},
    {"id": "MS31", "name": "Chill Score"},
    {"id": "MS32", "name": "Focus Score"}
    ]
    },
    {
    "id": "L21",
    "name": "Inter-Song Relationships",
    "markers": [
    {"id": "IR1", "name": "Sample Exact"},
    {"id": "IR2", "name": "Sample Modified"},
    {"id": "IR3", "name": "Sample Chopped"},
    {"id": "IR4", "name": "Sample Reversed"},
    {"id": "IR5", "name": "Interpolation Melodic"},
    {"id": "IR6", "name": "Interpolation Lyrical"},
    {"id": "IR7", "name": "Cover Exact"},
    {"id": "IR8", "name": "Cover Reimagined"},
    {"id": "IR9", "name": "Remix Club"},
    {"id": "IR10", "name": "Remix Dub"},
    {"id": "IR11", "name": "Remix Trap"},
    {"id": "IR12", "name": "Mashup"},
    {"id": "IR13", "name": "Genre Pop"},
    {"id": "IR14", "name": "Genre Rock"},
    {"id": "IR15", "name": "Genre HipHop"},
    {"id": "IR16", "name": "Genre R&B"},
    {"id": "IR17", "name": "Genre Electronic"},
    {"id": "IR18", "name": "Genre Country"},
    {"id": "IR19", "name": "Genre Jazz"},
    {"id": "IR20", "name": "Genre Classical"},
    {"id": "IR21", "name": "Genre Folk"},
    {"id": "IR22", "name": "Genre Blues"},
    {"id": "IR23", "name": "Genre Metal"},
    {"id": "IR24", "name": "Genre Punk"},
    {"id": "IR25", "name": "Genre Reggae"},
    {"id": "IR26", "name": "Genre Latin"},
    {"id": "IR27", "name": "Genre World"},
    {"id": "IR28", "name": "Genre Experimental"},
    {"id": "IR29", "name": "Sim Artist A"},
    {"id": "IR30", "name": "Sim Artist B"},
    {"id": "IR31", "name": "Sim Era 50s"},
    {"id": "IR32", "name": "Sim Era 60s"},
    {"id": "IR33", "name": "Sim Era 70s"},
    {"id": "IR34", "name": "Sim Era 80s"},
    {"id": "IR35", "name": "Sim Era 90s"},
    {"id": "IR36", "name": "Sim Era 00s"},
    {"id": "IR37", "name": "Sim Era 10s"},
    {"id": "IR38", "name": "Sim Era 20s"},
    {"id": "IR39", "name": "Sim Region US"},
    {"id": "IR40", "name": "Sim Region UK"},
    {"id": "IR41", "name": "Sim Region EU"},
    {"id": "IR42", "name": "Sim Region AS"},
    {"id": "IR43", "name": "Sim Region AF"},
    {"id": "IR44", "name": "Sim Region SA"},
    {"id": "IR45", "name": "Sim Region OC"},
    {"id": "IR46", "name": "Influence Beatles"},
    {"id": "IR47", "name": "Influence Kraftwerk"},
    {"id": "IR48", "name": "Influence James Brown"},
    {"id": "IR49", "name": "Influence Sabbath"},
    {"id": "IR50", "name": "Influence Dylan"},
    {"id": "IR51", "name": "Influence MJ"},
    {"id": "IR52", "name": "Influence Prince"},
    {"id": "IR53", "name": "Influence Madonna"},
    {"id": "IR54", "name": "Influence Nirvana"},
    {"id": "IR55", "name": "Influence Dre"},
    {"id": "IR56", "name": "Influence Daft Punk"},
    {"id": "IR57", "name": "Influence Kanye"},
    {"id": "IR58", "name": "Influence Skrillex"},
    {"id": "IR59", "name": "Influence Drake"},
    {"id": "IR60", "name": "Influence Swift"},
    {"id": "IR61", "name": "Uniqueness Score"},
    {"id": "IR62", "name": "Mainstream Score"},
    {"id": "IR63", "name": "Underground Score"},
    {"id": "IR64", "name": "Viral Potential"}
    ]
    },
    {
    "id": "L22",
    "name": "Production Fingerprint",
    "markers": [
    {"id": "PF1", "name": "Mono"},
    {"id": "PF2", "name": "Stereo Narrow"},
    {"id": "PF3", "name": "Stereo Wide"},
    {"id": "PF4", "name": "Stereo Extra-Wide"},
    {"id": "PF5", "name": "LCR Panning"},
    {"id": "PF6", "name": "Pan Dynamic"},
    {"id": "PF7", "name": "Depth Dry"},
    {"id": "PF8", "name": "Depth Wet"},
    {"id": "PF9", "name": "Balance Dark"},
    {"id": "PF10", "name": "Balance Bright"},
    {"id": "PF11", "name": "Balance Mid-focused"},
    {"id": "PF12", "name": "Balance Scooped"},
    {"id": "PF13", "name": "Dyn Range <4dB"},
    {"id": "PF14", "name": "Dyn Range 4-8dB"},
    {"id": "PF15", "name": "Dyn Range 8-12dB"},
    {"id": "PF16", "name": "Dyn Range >12dB"},
    {"id": "PF17", "name": "Peak Limiting"},
    {"id": "PF18", "name": "Soft Clipping"},
    {"id": "PF19", "name": "Hard Clipping"},
    {"id": "PF20", "name": "True Peak Overs"},
    {"id": "PF21", "name": "Noise Floor -40dB"},
    {"id": "PF22", "name": "Noise Floor -60dB"},
    {"id": "PF23", "name": "Noise Floor -80dB"},
    {"id": "PF24", "name": "Noise Floor Silent"},
    {"id": "PF25", "name": "Tape Saturation"},
    {"id": "PF26", "name": "Tube Saturation"},
    {"id": "PF27", "name": "Transistor Sat"},
    {"id": "PF28", "name": "Digital Clean"},
    {"id": "PF29", "name": "Bit Depth 8"},
    {"id": "PF30", "name": "Bit Depth 12"},
    {"id": "PF31", "name": "Bit Depth 16"},
    {"id": "PF32", "name": "Bit Depth 24+"},
    {"id": "PF33", "name": "Sample Rate <22k"},
    {"id": "PF34", "name": "Sample Rate 44.1k"},
    {"id": "PF35", "name": "Sample Rate 48k"},
    {"id": "PF36", "name": "Sample Rate 96k+"},
    {"id": "PF37", "name": "Mic Dynamic"},
    {"id": "PF38", "name": "Mic Condenser"},
    {"id": "PF39", "name": "Mic Ribbon"},
    {"id": "PF40", "name": "Mic Lo-Fi"},
    {"id": "PF41", "name": "Preamp Clean"},
    {"id": "PF42", "name": "Preamp Colored"},
    {"id": "PF43", "name": "Console Neve"},
    {"id": "PF44", "name": "Console SSL"},
    {"id": "PF45", "name": "Console API"},
    {"id": "PF46", "name": "In-the-box"},
    {"id": "PF47", "name": "Reverb Plate"},
    {"id": "PF48", "name": "Reverb Hall"},
    {"id": "PF49", "name": "Reverb Spring"},
    {"id": "PF50", "name": "Reverb Room"},
    {"id": "PF51", "name": "Reverb Gated"},
    {"id": "PF52", "name": "Reverb Reverse"},
    {"id": "PF53", "name": "Reverb Convolution"},
    {"id": "PF54", "name": "Reverb Algorithmic"},
    {"id": "PF55", "name": "Delay Slap"},
    {"id": "PF56", "name": "Delay Tape"},
    {"id": "PF57", "name": "Delay Digital"},
    {"id": "PF58", "name": "Delay Throw"},
    {"id": "PF59", "name": "Comp VCA"},
    {"id": "PF60", "name": "Comp FET"},
    {"id": "PF61", "name": "Comp Opto"},
    {"id": "PF62", "name": "Comp Vari-Mu"},
    {"id": "PF63", "name": "Comp Multiband"},
    {"id": "PF64", "name": "Comp Parallel"},
    {"id": "PF65", "name": "Sidechain Heavy"},
    {"id": "PF66", "name": "Sidechain Light"},
    {"id": "PF67", "name": "EQ Surgical"},
    {"id": "PF68", "name": "EQ Broad"},
    {"id": "PF69", "name": "EQ Passive"},
    {"id": "PF70", "name": "EQ Active"},
    {"id": "PF71", "name": "Pitch Correction None"},
    {"id": "PF72", "name": "Pitch Correction Transparent"},
    {"id": "PF73", "name": "Pitch Correction Hard"},
    {"id": "PF74", "name": "Vocoder"},
    {"id": "PF75", "name": "Editing Tight"},
    {"id": "PF76", "name": "Editing Loose"},
    {"id": "PF77", "name": "Loop Based"},
    {"id": "PF78", "name": "Linear Rec"},
    {"id": "PF79", "name": "Overdubbed"},
    {"id": "PF80", "name": "Live Take"},
    {"id": "PF81", "name": "Midi Quantized"},
    {"id": "PF82", "name": "Midi Humanized"},
    {"id": "PF83", "name": "Step Sequencer"},
    {"id": "PF84", "name": "Tracker"},
    {"id": "PF85", "name": "Mastering Vinyl"},
    {"id": "PF86", "name": "Mastering Cassette"},
    {"id": "PF87", "name": "Mastering CD"},
    {"id": "PF88", "name": "Mastering Streaming"},
    {"id": "PF89", "name": "Production Budget Low"},
    {"id": "PF90", "name": "Production Budget High"},
    {"id": "PF91", "name": "Indie Sound"},
    {"id": "PF92", "name": "Major Label Sound"},
    {"id": "PF93", "name": "Demo Quality"},
    {"id": "PF94", "name": "Broadcast Quality"},
    {"id": "PF95", "name": "Audiophile Quality"},
    {"id": "PF96", "name": "Radio Edit"}
    ]
    },
    {
    "id": "L23",
    "name": "Lyrical & Semantic",
    "markers": [
    {"id": "LS1", "name": "English"},
    {"id": "LS2", "name": "Spanish"},
    {"id": "LS3", "name": "Other Lang"},
    {"id": "LS4", "name": "Instrumental"},
    {"id": "LS5", "name": "Syllables/Sec Low"},
    {"id": "LS6", "name": "Syllables/Sec Med"},
    {"id": "LS7", "name": "Syllables/Sec High"},
    {"id": "LS8", "name": "Rhyme Perfect"},
    {"id": "LS9", "name": "Rhyme Slant"},
    {"id": "LS10", "name": "Rhyme Internal"},
    {"id": "LS11", "name": "Rhyme Multi-syllable"},
    {"id": "LS12", "name": "Structure AABB"},
    {"id": "LS13", "name": "Structure ABAB"},
    {"id": "LS14", "name": "Structure Free"},
    {"id": "LS15", "name": "Topic Love"},
    {"id": "LS16", "name": "Topic Heartbreak"},
    {"id": "LS17", "name": "Topic Party"},
    {"id": "LS18", "name": "Topic Social"},
    {"id": "LS19", "name": "Topic Introspective"},
    {"id": "LS20", "name": "Topic Story"},
    {"id": "LS21", "name": "Topic Abstract"},
    {"id": "LS22", "name": "Sentiment Positive"},
    {"id": "LS23", "name": "Sentiment Negative"},
    {"id": "LS24", "name": "Sentiment Neutral"},
    {"id": "LS25", "name": "Profanity None"},
    {"id": "LS26", "name": "Profanity Light"},
    {"id": "LS27", "name": "Profanity Heavy"},
    {"id": "LS28", "name": "Gender Male"},
    {"id": "LS29", "name": "Gender Female"},
    {"id": "LS30", "name": "Gender Group"},
    {"id": "LS31", "name": "Gender Androgynous"},
    {"id": "LS32", "name": "Vocal FX Heavy"}
    ]
    }
];